apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "node-chart.label" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "node-chart.label" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: MONGODB_URL
              value: mongodb://mongo:27017/database
          image: {{.Values.image.repository }}
          name:  {{ .Chart.Name }}
          resources:
            limits:
              cpu: 1100m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 3000
              hostPort: 4000
              protocol: TCP
      restartPolicy: Always
