version: "3"
services:
  mongo:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  swimlaneapp:
    build: .
    ports:
      - 4000:3000
    environment:
      MONGODB_URL: mongodb://mongo:27017/database
    depends_on:
      - mongo
volumes:
  mongo: {}

