apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: swimlaneapp
  name: swimlaneapp
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 3000
  selector:
    io.kompose.service: swimlaneapp
